#!/usr/bin/env bash
# This script was NOT executed in the authoring environment.
# It publishes only this project and its local Git history, never a transcript.
set -euo pipefail
cd "$(dirname "$0")/.."
command -v gh >/dev/null 2>&1 || { echo 'GitHub CLI (gh) is required.' >&2; exit 127; }
command -v lake >/dev/null 2>&1 || { echo 'Lean/Lake is required before publication.' >&2; exit 127; }
account="$(gh api user --jq .login)"
if [[ "$account" != 'xiangyazi24' ]]; then
  echo "Refusing to publish: authenticated account is $account, expected xiangyazi24." >&2
  exit 1
fi
if [[ -n "$(git status --porcelain)" ]]; then
  echo 'Refusing to publish a dirty worktree. Commit reviewed changes first.' >&2
  exit 1
fi
if git remote get-url origin >/dev/null 2>&1; then
  echo 'Refusing to replace an existing origin remote.' >&2
  exit 1
fi
# Both creation and push are gated on successful Lean verification.
lake update
lake exe cache get
./scripts/check.sh
# Record the manifest actually generated by Lake, not a hand-written substitute.
if [[ -f lake-manifest.json ]]; then
  git add lake-manifest.json
  if ! git diff --cached --quiet; then
    git commit -m 'chore: lock dependencies after successful Lean build'
  fi
fi
# gh refuses if the named repository already exists; it does not overwrite it.
gh repo create xiangyazi24/stanley-wilf --private --source . --remote origin --push
